export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<style>{`
			img{
				color: #000;
			}
			`}
			</style>
			<body>{children}</body>
		</html>
	);
}
